### PR TITLE
Fix functions help.

### PR DESCRIPTION
**Pull request by sethvs**
Fix help for Trace-xDscOperation, Get-xDscOperation and Update-xDscEventLogStatus functions.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdscdiagnostics/44)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 92 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBx6LnCIEKAh2vpQc_:-LDBx6LnCIEKAh2vpQca:bi6y8ry) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/README.md#L92)):*
> ```Markdown
> ## Versions
> 
> ### Unreleased
> ```

Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)`
```

---

*[xDscDiagnostics.psm1, line 60 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBxUHg-FfhdZEsrttJ:-LDBxUHg-FfhdZEsrttK:b-iidfoz) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L60)):*
> ```PowerShell
> .EXAMPLE
> Trace-xDscOperation 
> To Obtain the diagnostic information for the latest operation
> ```

Is there a reason you propose moving the text below the command instead of above?  (throughout)

---

*[xDscDiagnostics.psm1, line 75 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBxw1Q9PuMajj9qxxQ:-LDBxw1Q9PuMajj9qxxR:brxgvtr) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L75)):*
> ```PowerShell
> 
> 
> PS C:\>Trace-xDscOperation -Computername XYZ -Credential $mycredential -sequenceID 2
> ```

Maybe have this in a separate example?

---

*[xDscDiagnostics.psm1, line 75 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBy7-eESkj5N_OCbZZ:-LDBy7-eESkj5N_OCbZ_:b-2g2eag) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L75)):*
> ```
> PS C:\>
> ```

This isn't necessary (it seems to be added by Get-Help automatically)? Throughout.

---

*[xDscDiagnostics.psm1, line 85 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDByPjp8W6IJkEl3LRf:-LDByPjp8W6IJkEl3LRg:b-w1jq1n) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L85)):*
> ```PowerShell
> 
> 
> Please note that to perform actions on the remote computer, have the firewall for remote configuration enabled. This can be done with the following command:
> ```

Maybe add this to a .NOTES maybe? Since two examples depend on this information?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdscdiagnostics/44)*

**Comment by sethvs** [comment]
>Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.

Fixed.

> Is there a reason you propose moving the text below the command instead of above? (throughout)

To make it in accordance with the majority of another cmdlets' examples, where first line is the code, and others is the explanation.

> Maybe have this in a separate example?

This is mostly because of the note at the end of the example about firewall, which is of concern for all remoting examples. But, yes, I think it is better to separate these examples.

> This isn't necessary (it seems to be added by Get-Help automatically)? Throughout.

`PS C:\>` is added to the first line only, for all lines following it `PS C:\>` should be added manially.

> Maybe add this to a .NOTES maybe? Since two examples depend on this information?

Agree.

**Comment by johlju** [comment]
@sethvs thanks for answering my review comments.  Could you please go into Reviewable and write 'Done' (or click the done-button) on each of the review comments. This allows me to acknowledge (resolve) the review comments and I know that you are done with each change. After you written 'Done' on each review comment,  or comment on the review comment if it needs further discussion, then click the big green 'Publish' button on top of the page. That will send all your comments back as one big comment to this PR.
You find Reviewable if you click on the big purple Reviewable-button in the PR description.

**Comment by sethvs** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 92 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBx6LnCIEKAh2vpQc_:-LDM0lIG4CWy-jfWSQvf:b-896fix) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/README.md#L92)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)`
```
</blockquote></details>

Done.

---

*[xDscDiagnostics.psm1, line 60 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBxUHg-FfhdZEsrttJ:-LDM0qDVEfUwn-CUjMRK:b-896fix) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L60)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Is there a reason you propose moving the text below the command instead of above?  (throughout)
</blockquote></details>

Done.

---

*[xDscDiagnostics.psm1, line 75 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBxw1Q9PuMajj9qxxQ:-LDM0qou5GOzbf-6Sq5A:b-896fix) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe have this in a separate example?
</blockquote></details>

Done.

---

*[xDscDiagnostics.psm1, line 75 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDBy7-eESkj5N_OCbZZ:-LDM0rQm5LqLhECPLMw1:b-896fix) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> PS C:\>
> ```

This isn't necessary (it seems to be added by Get-Help automatically)? Throughout.
</blockquote></details>

Done.

---

*[xDscDiagnostics.psm1, line 85 at r1](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-LDByPjp8W6IJkEl3LRf:-LDM0sUk2GT7i4lAGPGv:b-896fix) ([raw file](https://github.com/powershell/xdscdiagnostics/blob/006837c75b53182e51d0d84b28e0900101164361/xDscDiagnostics.psm1#L85)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe add this to a .NOTES maybe? Since two examples depend on this information?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdscdiagnostics/44)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xdscdiagnostics/44#-:-LDM7NhkDBgPVWHJ29nm:bnfp4nl)*

**Comment by johlju** [comment]
@sethvs Thanks for this!

**Pull request merged**
